### ISSUE TITLE
Bugs in only-emote replies 

### ISSUE THREAD

**Issue by app6460** [taeseong14/chat#3]
![1650419712402](https://user-images.githubusercontent.com/65773837/164131222-efd24b66-8147-4291-9f28-4ecd404b46b6.jpg)
There is a bug where the html code is visible in the reply as shown in the picture above

**Comment by taeseong14** [comment]
화긴

**Comment by taeseong14** [comment]
![Screenshot](https://user-images.githubusercontent.com/88077395/164308756-595eb482-4f74-4427-8f40-724892bcd1a1.png)
Resolved.
