### ISSUE TITLE
버그이빈

### ISSUE THREAD

**Issue by dbswlstjr2** [taeseong14/chat#4]
입장하기 문구 이런것도 답장이 대빈다

**Comment by taeseong14** [comment]
그건 노린거빈다.

**Comment by taeseong14** [comment]
???: 버그가 아니고 기능인데요

**Comment by taeseong14** [comment]
아근대답장대상고쳐야하내재송

**Comment by taeseong14** [comment]
![Screenshot](https://user-images.githubusercontent.com/88077395/164338980-daac1d85-7ecf-41db-97c6-c634f02315e2.png)
Resolved.
