### ISSUE TITLE
previous chat bug 

### ISSUE THREAD

**Issue by app6460** [taeseong14/chat#5]
![1650423667244-1](https://user-images.githubusercontent.com/65773837/164141847-08c5367a-ef34-439c-8cee-4836756bba3d.jpg)
![1650423667244-0](https://user-images.githubusercontent.com/65773837/164141853-6e7a7c20-b59d-4a43-8a5c-37849f29bab4.jpg)
As shown in the picture, when you call up the previous chat, the reply disappears

**Comment by taeseong14** [comment]
![Screenshot](https://user-images.githubusercontent.com/88077395/164309890-84b14cad-24ff-4d0d-9d3f-5f8b2c4ce875.png)
Resolved.
