### ISSUE TITLE
화면 터치 버그(?)인가요

### ISSUE THREAD

**Issue by dbswlstjr2** [taeseong14/chat#9]
모바일은 화면 터치하면 멘밑으로 내려가던데 그게 아무것도 없는 회색 부분을 터치해도 멘밑으로 내려가네요

**Comment by taeseong14** [comment]
화면 터치시 키보드가 닫히면서 rezise이벤트가 작동하는 것 같습니다. 조금 더 자세한 설명을 들을 수 있을까요?
그리고 사용시에 많은 불편을 주나요?

**Comment by dbswlstjr2** [comment]
> 화면 터치시 키보드가 닫히면서 rezise이벤트가 작동하는 것 같습니다. 조금 더 자세한 설명을 들을 수 있을까요? 그리고 사용시에 많은 불편을 주나요?

그 스크롤을 멈춘다음에 클릭하면 멘 밑으로 채팅이 내려갑니다 그리고 회색배경화면을 클릭해도 내려가고요 사용시 답장기능을 사용할때 불편합니다

**Comment by taeseong14** [comment]
i'll fix that tommorow. thanks.

**Comment by taeseong14** [comment]
Resolved.
